This is a markdown cell

# Use # for a Heading
## Use ## for a Heading 2
### Use ### for a Heading 3

**Use ** - ** for bold text**

*Use * - * for italic text*

Bullet points
* Use a * for a bullit point
* And another *

Numbered points
1. Use 1. for a numbered point
2. And 2.

# Variable assignment

In [9]:
# declare variables
x = 5
x

5

# Data types and structures

## Integer (primitive)

In [12]:
a = 10
type(a)

int

## Float (primitive)

In [13]:
b = 2.1
type(b)

float

## String (primitive)

In [28]:
c = "Test this string with ' sign"
d = "This is a line with a \n break"
e = '"This is a quote" - Stan'
f = "\"This is also a quote\" - Stan"
g = "Print a \\"
print(c)
print(d)
print(e)
print(f)
print(g)
type(c)

# slicing (include first index, but excludes the last index)
print(f[3:])
print(f[:5])
print(f[1:5])

Test this string with ' sign
This is a line with a 
 break
"This is a quote" - Stan
"This is also a quote" - Stan
Print a \
is is also a quote" - Stan
"This
This


## Boolean (primitive)

In [30]:
d = True
print(type(d))

h = 1
i = 2
h == i

<class 'bool'>


False

## List (non-primitive)

In [62]:
a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a_list)

# combine datatype into one list
b_list = [1, 2, 3, "String", True, [1, 3, 6]]
print(b_list)

# slicing
print(b_list[2])
print(b_list[5][2])

# slicing and skipping data
print(b_list[2:7:2])
print(b_list[-1])       # last value from list
print(b_list[::-1])     # reverse a list

# set value in list
c_list = b_list.copy()
c_list[0] = 100
print(c_list)

# add one value to list
c_list.append(200)
print(c_list)

# add multiple values to list
c_list.extend([300, 301, 302])
print(c_list)

# add value at specific indix
c_list.insert(2, "Inserted at index 2")
print(c_list)

# remove value from list
c_list.remove(2)
print(c_list)

# remove value at specific index
c_list.pop(3)
print(c_list)

# resverse a list
c_list.reverse()
print(c_list)

# length of a list
print(len(c_list))

# count number of occurences of a values in list
print(c_list.count(200))

# add two lists together
concat_list = b_list + c_list
print(concat_list)

# multiply a list
multiply_list = c_list * 2
print(multiply_list)

# find index of first occurence of value
print(multiply_list.index(200))

# sort a list
sort_list = [2, 5, 1, 3, 8]
sort_list.sort()
print(sort_list)

# truncate the list
sort_list.clear()
print(sort_list)

# list of all list operations: https://www.educba.com/list-operations-in-python/


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 'String', True, [1, 3, 6]]
3
6
[3, True]
[1, 3, 6]
[[1, 3, 6], True, 'String', 3, 2, 1]
[100, 2, 3, 'String', True, [1, 3, 6]]
[100, 2, 3, 'String', True, [1, 3, 6], 200]
[100, 2, 3, 'String', True, [1, 3, 6], 200, 300, 301, 302]
[100, 2, 'Inserted at index 2', 3, 'String', True, [1, 3, 6], 200, 300, 301, 302]
[100, 'Inserted at index 2', 3, 'String', True, [1, 3, 6], 200, 300, 301, 302]
[100, 'Inserted at index 2', 3, True, [1, 3, 6], 200, 300, 301, 302]
[302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100]
9
1
[1, 2, 3, 'String', True, [1, 3, 6], 302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100]
[302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100, 302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100]
3
[1, 2, 3, 5, 8]
[]


## Tuple (non-primitive)

In [63]:
# a tuple is a list that cannot be modified
# main use are outputs of python methods or classes
a_tuple = (1, 2, 3, 4, 5)

## Dictionary (non-primitive)

In [69]:
# key, value pairs
# can be useful when working with tables
a_dict = {"key":"value", "multiple":[1, 2, 3, 4]}

# get a value from the dictionary using the key
print(a_dict.get("multiple"))
print(a_dict["multiple"])


[1, 2, 3, 4]
[1, 2, 3, 4]


## Set (non-primitive)

In [70]:
# an unordered, unchangeable way to store multiple variables without duplicates
a_set = {"Value", 1, 2, 1}
print(a_set)

{1, 2, 'Value'}


# Operations

## Arithmetic

In [78]:
# add
add = 2 + 3
mult_list = [1, 2, 3] * 3
print(mult_list)

str_add = "str" + "str"
print(str_add)

# modulo
modulo = 10 % 3  # Gives you the the remainder of a division operation
print(modulo)

# floor division
floor_division = 7 // 2  # Gives you the largest multiple, in this case it's 3
print(floor_division)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
strstr
1
3


## Assignment

In [76]:
# see https://www.w3schools.com/python/python_operators.asp
a = 3
a *= 3
print(a)

9


## Comparison

In [80]:
print(3 == 3)  # Equals

print(3 != 4)  # Does not equal

print(3 > 4)  # Greater than

print(3 < 5) # Less than

print(2 >= 2)  # Greater than or equal to

print(4 <= 4)  # Less than or equal to

True
True
False
True
True
True


## Bitwise

In [81]:
# see: https://wiki.python.org/moin/BitwiseOperators

## Logical operators

In [82]:
3 == 3 and 2 <= 5  # Returns true if both operations are true
3 == 3 or 2 <= 1  # Returns true if one operation is true
not(3 == 3 and 2 <= 5)  # Returns the opposite (False in this case)

False

## Membership

In [83]:
"T" in "TRDFSADFASD"
"z" not in ["a", 123, 14, 41, 41, 4]

True

# Functions

In [84]:
def function_name(x, y, z):
	return x + y + z  # The "return" tells Python what to output from a function


function_name(x=1, y=2, z=3)  # This is how we call a function

# You can also call it like this by letting Python assume your arguments are in order
function_name(1, 2, 3)

# You can also not specify earlier arguments, but specify later ones
function_name(1, 2, z=4)

# This is not valid (Python doesn't know what arguments to match 2 and 3 with
# function_name(x=1, 2, 3)


7

# Control statements

## For loop

In [86]:
# range creates a sequence of values between the two arguments
the_list = range(3, 10)

for i in the_list:  # This is how you start a for loop
    i += 2  # "i" represents the value of the sequence you're on
    print(i)


5
6
7
8
9
10
11


## While loop

In [87]:
x = 0

while x < 5:  # The condition that has to be true for this loop to continue
    x += 1  # These are the calculations that are performed each loop
    print(x)


1
2
3
4
5


## If - then

In [88]:
x = 3
y = 5

if x == y:
    print("x equals y")
elif x > y:
    print("x is greater than y")
else:
    print("x is less than y")


x is less than y


## Try - except

In [1]:
try:
    2 / 0  # You can't divide by 0 and this will throw an exception
except ZeroDivisionError:
    print("Can't divide by 0")


Can't divide by 0


## With

In [3]:
# see https://www.geeksforgeeks.org/with-statement-in-python/
# often used for opening and reading files

with open('dog_breeds.txt', 'rb') as reader:
	print("File has been read")

FileNotFoundError: [Errno 2] No such file or directory: 'dog_breeds.txt'

# NumPy

## Arays

In [12]:
import numpy as np

# always use a list to create an array in NumPy
a = np.array([2,3,4])
print(a)

# 2-dimensional array
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
print(c)

# 3-dimensional array
d = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)
print(d)


[2 3 4]
[[2 3 4]
 [5 6 2]]
[[[2 3]
  [4 5]]

 [[6 2]
  [3 5]]]


## NumPy calculations

In [14]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum())  # Sum the array
print(e.min())  # Find the minimum value in an array
print(e.max())  # Find the maximum value in an array
print(e.mean())  # Find the arithmetic mean of an array


21
1
6
3.5


## Special NumPy arrays

In [16]:
print(np.zeros(5))  # Creates an array of zeros with 5 elements
# Creates an array of values from 0 through 6 in 10 even spaces
print(np.linspace(0, 6, 10))
print(np.random.rand(3))  # Three random values between 0 and 1
print(np.random.randint(1, 1000))  # A random integer between 1 and 1000
# Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25
print(np.arange(25))


[0. 0. 0. 0. 0.]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
[0.32091911 0.9737301  0.23607773]
931
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
