This is a markdown cell

# Use # for a Heading
## Use ## for a Heading 2
### Use ### for a Heading 3

**Use ** - ** for bold text**

*Use * - * for italic text*

Bullet points
* Use a * for a bullit point
* And another *

Numbered points
1. Use 1. for a numbered point
2. And 2.

# Variable assignment

In [9]:
# declare variables
x = 5
x

5

# Data types and structures

## Integer (primitive)

In [12]:
a = 10
type(a)

int

## Float (primitive)

In [13]:
b = 2.1
type(b)

float

## String (primitive)

In [28]:
c = "Test this string with ' sign"
d = "This is a line with a \n break"
e = '"This is a quote" - Stan'
f = "\"This is also a quote\" - Stan"
g = "Print a \\"
print(c)
print(d)
print(e)
print(f)
print(g)
type(c)

# slicing (include first index, but excludes the last index)
print(f[3:])
print(f[:5])
print(f[1:5])

Test this string with ' sign
This is a line with a 
 break
"This is a quote" - Stan
"This is also a quote" - Stan
Print a \
is is also a quote" - Stan
"This
This


## Boolean (primitive)

In [30]:
d = True
print(type(d))

h = 1
i = 2
h == i

<class 'bool'>


False

## List (non-primitive)

In [62]:
a_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a_list)

# combine datatype into one list
b_list = [1, 2, 3, "String", True, [1, 3, 6]]
print(b_list)

# slicing
print(b_list[2])
print(b_list[5][2])

# slicing and skipping data
print(b_list[2:7:2])
print(b_list[-1])       # last value from list
print(b_list[::-1])     # reverse a list

# set value in list
c_list = b_list.copy()
c_list[0] = 100
print(c_list)

# add one value to list
c_list.append(200)
print(c_list)

# add multiple values to list
c_list.extend([300, 301, 302])
print(c_list)

# add value at specific indix
c_list.insert(2, "Inserted at index 2")
print(c_list)

# remove value from list
c_list.remove(2)
print(c_list)

# remove value at specific index
c_list.pop(3)
print(c_list)

# resverse a list
c_list.reverse()
print(c_list)

# length of a list
print(len(c_list))

# count number of occurences of a values in list
print(c_list.count(200))

# add two lists together
concat_list = b_list + c_list
print(concat_list)

# multiply a list
multiply_list = c_list * 2
print(multiply_list)

# find index of first occurence of value
print(multiply_list.index(200))

# sort a list
sort_list = [2, 5, 1, 3, 8]
sort_list.sort()
print(sort_list)

# truncate the list
sort_list.clear()
print(sort_list)

# list of all list operations: https://www.educba.com/list-operations-in-python/


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 'String', True, [1, 3, 6]]
3
6
[3, True]
[1, 3, 6]
[[1, 3, 6], True, 'String', 3, 2, 1]
[100, 2, 3, 'String', True, [1, 3, 6]]
[100, 2, 3, 'String', True, [1, 3, 6], 200]
[100, 2, 3, 'String', True, [1, 3, 6], 200, 300, 301, 302]
[100, 2, 'Inserted at index 2', 3, 'String', True, [1, 3, 6], 200, 300, 301, 302]
[100, 'Inserted at index 2', 3, 'String', True, [1, 3, 6], 200, 300, 301, 302]
[100, 'Inserted at index 2', 3, True, [1, 3, 6], 200, 300, 301, 302]
[302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100]
9
1
[1, 2, 3, 'String', True, [1, 3, 6], 302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100]
[302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100, 302, 301, 300, 200, [1, 3, 6], True, 3, 'Inserted at index 2', 100]
3
[1, 2, 3, 5, 8]
[]


## Tuple (non-primitive)

In [63]:
# a tuple is a list that cannot be modified
# main use are outputs of python methods or classes
a_tuple = (1, 2, 3, 4, 5)

## Dictionary (non-primitive)

In [69]:
# key, value pairs
# can be useful when working with tables
a_dict = {"key":"value", "multiple":[1, 2, 3, 4]}

# get a value from the dictionary using the key
print(a_dict.get("multiple"))
print(a_dict["multiple"])


[1, 2, 3, 4]
[1, 2, 3, 4]


## Set (non-primitive)

In [70]:
# an unordered, unchangeable way to store multiple variables without duplicates
a_set = {"Value", 1, 2, 1}
print(a_set)

{1, 2, 'Value'}


# Operations

## Arithmetic

In [78]:
# add
add = 2 + 3
mult_list = [1, 2, 3] * 3
print(mult_list)

str_add = "str" + "str"
print(str_add)

# modulo
modulo = 10 % 3  # Gives you the the remainder of a division operation
print(modulo)

# floor division
floor_division = 7 // 2  # Gives you the largest multiple, in this case it's 3
print(floor_division)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
strstr
1
3


## Assignment

In [76]:
# see https://www.w3schools.com/python/python_operators.asp
a = 3
a *= 3
print(a)

9


## Comparison

In [80]:
print(3 == 3)  # Equals

print(3 != 4)  # Does not equal

print(3 > 4)  # Greater than

print(3 < 5) # Less than

print(2 >= 2)  # Greater than or equal to

print(4 <= 4)  # Less than or equal to

True
True
False
True
True
True


## Bitwise

In [81]:
# see: https://wiki.python.org/moin/BitwiseOperators

## Logical operators

In [82]:
3 == 3 and 2 <= 5  # Returns true if both operations are true
3 == 3 or 2 <= 1  # Returns true if one operation is true
not(3 == 3 and 2 <= 5)  # Returns the opposite (False in this case)

False

## Membership

In [83]:
"T" in "TRDFSADFASD"
"z" not in ["a", 123, 14, 41, 41, 4]

True

# Functions

In [84]:
def function_name(x, y, z):
	return x + y + z  # The "return" tells Python what to output from a function


function_name(x=1, y=2, z=3)  # This is how we call a function

# You can also call it like this by letting Python assume your arguments are in order
function_name(1, 2, 3)

# You can also not specify earlier arguments, but specify later ones
function_name(1, 2, z=4)

# This is not valid (Python doesn't know what arguments to match 2 and 3 with
# function_name(x=1, 2, 3)


7

# Control statements

## For loop

In [86]:
# range creates a sequence of values between the two arguments
the_list = range(3, 10)

for i in the_list:  # This is how you start a for loop
    i += 2  # "i" represents the value of the sequence you're on
    print(i)


5
6
7
8
9
10
11


## While loop

In [87]:
x = 0

while x < 5:  # The condition that has to be true for this loop to continue
    x += 1  # These are the calculations that are performed each loop
    print(x)


1
2
3
4
5


## If - then

In [88]:
x = 3
y = 5

if x == y:
    print("x equals y")
elif x > y:
    print("x is greater than y")
else:
    print("x is less than y")


x is less than y


## Try - except

In [1]:
try:
    2 / 0  # You can't divide by 0 and this will throw an exception
except ZeroDivisionError:
    print("Can't divide by 0")


Can't divide by 0


## With

In [3]:
# see https://www.geeksforgeeks.org/with-statement-in-python/
# often used for opening and reading files

with open('dog_breeds.txt', 'rb') as reader:
	print("File has been read")

FileNotFoundError: [Errno 2] No such file or directory: 'dog_breeds.txt'

# NumPy

## Arays

In [12]:
import numpy as np

# always use a list to create an array in NumPy
a = np.array([2,3,4])
print(a)

# 2-dimensional array
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
print(c)

# 3-dimensional array
d = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)
print(d)


[2 3 4]
[[2 3 4]
 [5 6 2]]
[[[2 3]
  [4 5]]

 [[6 2]
  [3 5]]]


## NumPy calculations

In [14]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum())  # Sum the array
print(e.min())  # Find the minimum value in an array
print(e.max())  # Find the maximum value in an array
print(e.mean())  # Find the arithmetic mean of an array


21
1
6
3.5


## Special NumPy arrays

In [16]:
print(np.zeros(5))  # Creates an array of zeros with 5 elements
# Creates an array of values from 0 through 6 in 10 even spaces
print(np.linspace(0, 6, 10))
print(np.random.rand(3))  # Three random values between 0 and 1
print(np.random.randint(1, 1000))  # A random integer between 1 and 1000
# Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25
print(np.arange(25))


[0. 0. 0. 0. 0.]
[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]
[0.32091911 0.9737301  0.23607773]
931
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


# Pandas

In [23]:
import pandas as pd

## Series

In [22]:
# the basis of pandas are dataframes
# they consist of series: an indexed list of numbers

# this is list
series_list = list(range(1,100))
series_list

# create a series
pd.Series(series_list)

0      1
1      2
2      3
3      4
4      5
      ..
94    95
95    96
96    97
97    98
98    99
Length: 99, dtype: int64

## Dataframe

In [64]:
# a dataframe is a couple of series stacked next to each other as columns
# we use simple_csv data for this purpose

import os
import pandas as pd

cwd = os.getcwd()
filepath = cwd + "/data - simple_csv.csv"
first_import = pd.read_csv(filepath)  # This reads the csv into Python
first_import # this is a dataframe (there is an index column)


Column1   Column2   Column3
0   0.280925  0.910368  0.692982
1   0.719882  0.210024  0.761276
2   0.235752  0.059796  0.154667
3   0.603366  0.485614  0.013345
4   0.039985  0.236359  0.811832
5   0.015478  0.543641  0.112719
6   0.192540  0.409874  0.875082
7   0.380921  0.045468  0.515859
8   0.592471  0.786421  0.047249
9   0.072112  0.695694  0.409573
10  0.898072  0.070956  0.209020
11  0.722038  0.211985  0.324164
12  0.513517  0.091548  0.664279
13  0.436729  0.040322  0.548167
14  0.864039  0.963556  0.106398
15  0.724761  0.410422  0.587589
16  0.198926  0.245207  0.767356
17  0.748500  0.019264  0.046678
18  0.920639  0.212611  0.520463
19  0.452024  0.123660  0.847451
20  0.542977  0.265852  0.410926
21  0.355266  0.860616  0.589431
22  0.142688  0.406456  0.204095
23  0.850436  0.129426  0.719027
24  0.443476  0.388967  0.596924
25  0.467100  0.416908  0.098037
26  0.338536  0.935814  0.736899
27  0.942101  0.772005  0.441574
28  0.570130  0.780085  0.085592

## Columns

In [78]:
# you can use either of these techniques to specify a column in a table. 
# I prefer the second one because it allows your column names to have spaces in them

first_import.Column1
first_import["Column1"]

0     0.280925
1     0.719882
2     0.235752
3     0.603366
4     0.039985
5     0.015478
6     0.192540
7     0.380921
8     0.592471
9     0.072112
10    0.898072
11    0.722038
12    0.513517
13    0.436729
14    0.864039
15    0.724761
16    0.198926
17    0.748500
18    0.920639
19    0.452024
20    0.542977
21    0.355266
22    0.142688
23    0.850436
24    0.443476
25    0.467100
26    0.338536
27    0.942101
28    0.570130
Name: Column1, dtype: float64

In [76]:
# create and drop a column

# You can specify a uniform value for every row
first_import["new_column_uniform"] = 1

# You can pass a list of values that is as long as the DataFrame
first_import["new_column_range"] = range(29)

# You can take a couple of columns and add their values together
first_import["Adding Stuff"] = first_import["Column3"] + first_import["Column1"]

first_import_new = first_import.drop(columns="new_column_uniform")

# The "drop" method creates a copy of the DataFrame. If you want to change the original DataFrame either do what we did in the line above, or use the "inplace" argument
first_import.drop(columns="new_column_uniform", inplace=True)

first_import
first_import_new


Column1   Column2   Column3  new_column_range  Adding Stuff
0   0.280925  0.910368  0.692982                 0      0.973907
1   0.719882  0.210024  0.761276                 1      1.481158
2   0.235752  0.059796  0.154667                 2      0.390419
3   0.603366  0.485614  0.013345                 3      0.616711
4   0.039985  0.236359  0.811832                 4      0.851816
5   0.015478  0.543641  0.112719                 5      0.128197
6   0.192540  0.409874  0.875082                 6      1.067622
7   0.380921  0.045468  0.515859                 7      0.896780
8   0.592471  0.786421  0.047249                 8      0.639721
9   0.072112  0.695694  0.409573                 9      0.481685
10  0.898072  0.070956  0.209020                10      1.107093
11  0.722038  0.211985  0.324164                11      1.046201
12  0.513517  0.091548  0.664279                12      1.177795
13  0.436729  0.040322  0.548167                13      0.984896
14  0.864039  0.963556  0.106398                14      0.970438
15  0.724761  0.410422  0.587589                15      1.312350
16  0.198926  0.245207  0.767356                16      0.966282
17  0.748500  0.019264  0.046678                17      0.795178
18  0.920639  0.212611  0.520463                18      1.441103
19  0.452024  0.123660  0.847451                19      1.299475
20  0.542977  0.265852  0.410926                20      0.953903
21  0.355266  0.860616  0.589431                21      0.944697
22  0.142688  0.406456  0.204095                22      0.346783
23  0.850436  0.129426  0.719027                23      1.569464
24  0.443476  0.388967  0.596924                24      1.040399
25  0.467100  0.416908  0.098037                25      0.565137
26  0.338536  0.935814  0.736899                26      1.075435
27  0.942101  0.772005  0.441574                27      1.383675
28  0.570130  0.780085  0.085592                28      0.655722

## Rows

In [88]:
# The `loc` method allows us to use the names of columns to specify them.
# select all rows from Column1
first_import.loc[:, "Column1"]

# Select rows 0 through 4 INCLUSIVE (different from other Python indices) in Column1
first_import.loc[0:4, "Column1"]

# Select all rows in Column1 and Column2
first_import.loc[:, ["Column1", "new_column_range"]]


# An `iloc` query is based off of normal numerical indexing but operates mostly the same way:
# Select all rows in Column1
first_import.iloc[:, 1]  
first_import.iloc[0:4, 1] # Select rows 0 through 4 excluding 4 (different from other Python indices) in Column1

# Select rows 0 through 4 excluding 4 (different from other Python indices) in Column1
first_import.iloc[0:4, 1]

# Select all rows in Column1 and Column2
first_import.iloc[:, 0:2]  

# Select all rows in Column1 and Column3
first_import.iloc[:, [0,2]]


Column1   Column3
0   0.280925  0.692982
1   0.719882  0.761276
2   0.235752  0.154667
3   0.603366  0.013345
4   0.039985  0.811832
5   0.015478  0.112719
6   0.192540  0.875082
7   0.380921  0.515859
8   0.592471  0.047249
9   0.072112  0.409573
10  0.898072  0.209020
11  0.722038  0.324164
12  0.513517  0.664279
13  0.436729  0.548167
14  0.864039  0.106398
15  0.724761  0.587589
16  0.198926  0.767356
17  0.748500  0.046678
18  0.920639  0.520463
19  0.452024  0.847451
20  0.542977  0.410926
21  0.355266  0.589431
22  0.142688  0.204095
23  0.850436  0.719027
24  0.443476  0.596924
25  0.467100  0.098037
26  0.338536  0.736899
27  0.942101  0.441574
28  0.570130  0.085592

## Columns and filtering

In [101]:
netflix = pd.read_csv(cwd + "/data - netflix_titles.csv")
netflix

# list out columns
netflix.columns

# basic descriptive statistics
netflix.describe()

# see unique values in a column
netflix["type"].unique()

# filter a dataframe
netflix[netflix["country"]=="Singapore"]
netflix[(netflix["country"] == "Singapore") & (netflix["rating"] == "TV-MA")]


show_id     type                           title       director  \
2093   s2094    Movie      Fakkah Fuzz: Almost Banned  Michael McKay   
2956   s2957    Movie                       Imperfect    Steve Cheng   
3528   s3529    Movie                       Lang Tong        Sam Loh   
4138   s4139    Movie  Miss J Contemplates Her Choice      Jason Lai   
6949   s6950  TV Show               The Truth Seekers            NaN   

                                                   cast    country  \
2093                                        Fakkah Fuzz  Singapore   
2956  Edwin Goh, Ian Fang Weijie, Phua Yida, Kimberl...  Singapore   
3528  William Lawandi, Angeline Yap, Vivienne Tseng,...  Singapore   
4138  Kit Chan, Xiang Yun, Bobby Tonelli, Shane Pow,...  Singapore   
6949  Chen Hanwei, Rebecca Lim, Desmond Tan, Yusuke ...  Singapore   

             date_added  release_year rating  duration  \
2093   January 26, 2018          2018  TV-MA    61 min   
2956  December 20, 2018          2012  TV-MA    95 min   
3528  December 20, 2018          2015  TV-MA    82 min   
4138  December 20, 2018          2014  TV-MA    89 min   
6949       July 1, 2017          2016  TV-MA  1 Season   

                                              listed_in  \
2093                                    Stand-Up Comedy   
2956           Action & Adventure, International Movies   
3528                    International Movies, Thrillers   
4138            Dramas, International Movies, Thrillers   
6949  Crime TV Shows, International TV Shows, TV Dramas   

                                            description  
2093  Stand-up comic Fakkah Fuzz mines cross-cultura...  
2956  After a brawl lands him in a Boys’ Home, a tee...  
3528  After seducing a philandering con man, a rebel...  
4138  The life of a radio talk-show host is turned u...  
6949  A veteran cop forms an agency dedicated to sol...

## DateTimes

In [110]:
# transform date to computer date
netflix["computer_date"] = pd.to_datetime(netflix["date_added"])

# fill in NaT values
import datetime
netflix["computer_date"].fillna(datetime.datetime(2020, 1, 1), inplace=True)

# Unix Time (counts up for every second since 01-01-1970)
netflix["nix_time"] = netflix["computer_date"].astype(int)
netflix

/var/folders/jg/1ck3yxvn1sn72cwsg5c615740000gn/T/ipykernel_1763/3488847360.py:9: FutureWarning: casting datetime64[ns] values to int64 with .astype(...) is deprecated and will raise in a future version. Use .view(...) instead.
  netflix["nix_time"] = netflix["computer_date"].astype(int)


show_id     type                                    title  \
0         s1  TV Show                                       3%   
1         s2    Movie                                     7:19   
2         s3    Movie                                    23:59   
3         s4    Movie                                        9   
4         s5    Movie                                       21   
...      ...      ...                                      ...   
7782   s7783    Movie                                     Zozo   
7783   s7784    Movie                                   Zubaan   
7784   s7785    Movie                        Zulu Man in Japan   
7785   s7786  TV Show                    Zumbo's Just Desserts   
7786   s7787    Movie  ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS   

               director                                               cast  \
0                   NaN  João Miguel, Bianca Comparato, Michel Gomes, R...   
1     Jorge Michel Grau  Demián Bichir, Héctor Bonilla, Oscar Serrano, ...   
2          Gilbert Chan  Tedd Chan, Stella Chung, Henley Hii, Lawrence ...   
3           Shane Acker  Elijah Wood, John C. Reilly, Jennifer Connelly...   
4        Robert Luketic  Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...   
...                 ...                                                ...   
7782        Josef Fares  Imad Creidi, Antoinette Turk, Elias Gergi, Car...   
7783        Mozez Singh  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...   
7784                NaN                                            Nasty C   
7785                NaN                         Adriano Zumbo, Rachel Khoo   
7786           Sam Dunn                                                NaN   

                                                country          date_added  \
0                                                Brazil     August 14, 2020   
1                                                Mexico   December 23, 2016   
2                                             Singapore   December 20, 2018   
3                                         United States   November 16, 2017   
4                                         United States     January 1, 2020   
...                                                 ...                 ...   
7782  Sweden, Czech Republic, United Kingdom, Denmar...    October 19, 2020   
7783                                              India       March 2, 2019   
7784                                                NaN  September 25, 2020   
7785                                          Australia    October 31, 2020   
7786              United Kingdom, Canada, United States       March 1, 2020   

      release_year rating   duration  \
0             2020  TV-MA  4 Seasons   
1             2016  TV-MA     93 min   
2             2011      R     78 min   
3             2009  PG-13     80 min   
4             2008  PG-13    123 min   
...            ...    ...        ...   
7782          2005  TV-MA     99 min   
7783          2015  TV-14    111 min   
7784          2019  TV-MA     44 min   
7785          2019  TV-PG   1 Season   
7786          2019  TV-MA     90 min   

                                              listed_in  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...   
1                          Dramas, International Movies   
2                   Horror Movies, International Movies   
3     Action & Adventure, Independent Movies, Sci-Fi...   
4                                                Dramas   
...                                                 ...   
7782                       Dramas, International Movies   
7783     Dramas, International Movies, Music & Musicals   
7784  Documentaries, International Movies, Music & M...   
7785                 International TV Shows, Reality TV   
7786                    Documentaries, Music & Musicals   

                                            description computer_date  \
0     In a future where the elite inhabit an island ...    2020

## Splitting and renaming columns + dealing with NaN

In [125]:
# splitting a column
netflix[["month_day", "year"]] = netflix["date_added"].str.split(", ", expand=True)

# renaming a column
netflix.rename(columns={"year": "year_adjusted"}, inplace=True)

# dealing with NaN
netflix["cast"].fillna(value="no cast", inplace=True)


/Users/stanvanklink/opt/miniconda3/envs/minimal_ds/lib/python3.9/site-packages/pandas/core/generic.py:6392: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
